### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by isaquliyev**
We have implemented get() and count() methods for both storage types; FileStorage and DBStorage. Tests for FileStorage are ready, but I don't know how to write tests for DBStorage.
In my opinion, we can change the TestDBStorage later. Let's don't waste time on it.

### CODE REVIEW

**Review by farid-hashimzada — CHANGES_REQUESTED** [review]
We have database hbnb_test_db. You can use it for testing purposes. If it is hard to work with orm, feel free to use MySQLdb

**Comment by isaquliyev** [comment]
I face problems when I use environmental variables for testing. I just changed the name of class.

**Review by farid-hashimzada — APPROVED** [review]
Ok, we can update it later, don't worry.

**Comment by farid-hashimzada** [comment]
no problem

**Pull request merged**
